/* Project: Vehicular Cloud Real Time System (VCRTS)
 * Class: Client.java
 * Authors: Group 2 (Justin Cracchiolo, Lauren Rodriguez, David Choi, Tristan Huertas, Ivan Lin, Anthony Vallejo, and Sebastian Villavicencio)
 * Date: February 2026
 * The Client class represents a consumer in the VCRTS system who submits computational jobs. It stores the client's ID, approximate job duration,
 * and job deadline, and extends the User class to inherit authentication properties such as username and password.
 */
package classes;

import java.util.ArrayList;

// ---------------------------------------------------------------
// utilizes the User class to set client username and password
public class Client extends User {

    //--------------------------------------------
    private ArrayList<Job> clientJobs = new ArrayList<>();
    // private String clientId; 
    // private static int increment = 0;

    //--------------------------------------------
    /**
     * constructor for the client class; utilizes the constructor of the User
     * class to set the username and password
     */
    public Client(String username, String password) {
        this(username, password, "");
    }

    //--------------------------------------------
    public Client(String username, String password, String email) {
        super(username, password, email, "Client");
        // increment++;
        // this.clientId = Integer.toString(increment); // set clientId to the userId generated by the User class constructor
    }

    //--------------------------------------------
    public Client(String username, String password, String email, String userId) {
        super(username, password, userId, email, "Client");
    }

    //--------------------------------------------
    // Adds a job to the client's list of jobs.
    public void addJob(Job job) {
        clientJobs.add(job);
    }

    //--------------------------------------------
    // @return client's list of jobs
    public ArrayList<Job> getClientJobs() {
        return clientJobs;
    }

    public void removeJob(Job j) {
        clientJobs.remove(j);
        Admin.removeJob(j);
    }
}
